# Generated by Django 4.0.1 on 2022-09-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_level'),
        ('core', '0004_alter_evaluationsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationsubmission',
            unique_together={('evaluationInfo', 'submitter')},
        ),
    ]
