# Generated by Django 4.0.1 on 2022-09-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='programinformation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
    ]
