# Generated by Django 4.0.1 on 2022-11-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_courseinformation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='course_group',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend'), ('modular', 'Modular')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='qualification_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programinformation'),
        ),
    ]
