# Generated by Django 4.0.1 on 2022-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_courseinformation_qualification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinformation',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
