# Generated by Django 4.0.1 on 2022-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_level'),
        ('core', '0013_alter_evaluationsubmission_assignments_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
