# Generated by Django 4.0.1 on 2022-06-09 10:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_course_group_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[accounts.models.validate_gimpa_email]),
        ),
    ]
