# Generated by Django 4.0.1 on 2022-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
