# Generated by Django 4.0.1 on 2022-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_lecturerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='staff_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
