# Generated by Django 4.0.1 on 2022-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[(0, 'Diploma'), (100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400'), (600, 'Level 600-PGD'), (700, 'Level 700'), (800, 'Level 800')], max_length=30, null=True),
        ),
    ]
