# Generated by Django 4.0.1 on 2022-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('000', 'Diploma'), ('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('600', 'Level 600-PGD'), ('700', 'Level 700'), ('800', 'Level 800')], max_length=30, null=True),
        ),
    ]
