# Generated by Django 4.0.1 on 2022-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period_of_study', models.IntegerField(blank=True, null=True)),
                ('lecturer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturer_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'School Data',
                'verbose_name_plural': 'School Data',
            },
        ),
    ]