# Generated by Django 4.0.1 on 2022-06-02 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_feedback_beginning_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_course_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_lecture_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_outcomes_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_procedures_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_books_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_schedule', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_punctuality', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_presence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_enthusiasm', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_sequence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_organization', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_clarity', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_contents', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_responsiveness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_achievements', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_innovation', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_theory_practices', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_relevance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_promptitude', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_feedback', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_guidance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_availability', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_help', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_fairness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_classroom_size', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_seats', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_audio_visual_equip', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_public_address', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_books', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_computers', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_internet', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_air_conditioning', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_secretariat', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('evaluationInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_form', to='core.courseinformation')),
            ],
            options={
                'unique_together': {('evaluationInfo',)},
            },
        ),
    ]
