# Generated by Django 4.0.1 on 2022-06-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evaluation_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
    ]
