# Generated by Django 4.0.1 on 2022-06-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_campus'),
        ('core', '0006_campusinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
    ]
