# Generated by Django 4.0.1 on 2022-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evaluationsubmission_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='lecturer_name',
        ),
        migrations.RemoveField(
            model_name='courseinformation',
            name='lecturer_surname',
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='lecturer_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
