# Generated by Django 4.0.1 on 2022-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_courseinformation_lecturer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='semester',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
