# Generated by Django 4.0.1 on 2022-08-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courseinformation_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='course_group',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=255, null=True),
        ),
    ]
