# Generated by Django 4.0.1 on 2022-08-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courseinformation_course_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='period_of_study',
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='level',
            field=models.CharField(choices=[('000', 'Diploma'), ('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('600', 'Level 600-PGD'), ('700', 'Level 700'), ('800', 'Level 800')], max_length=30, null=True),
        ),
    ]
