# Generated by Django 4.0.1 on 2022-08-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_courseinformation_period_of_study_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinformation',
            options={'verbose_name': 'Course Data', 'verbose_name_plural': 'Course Data'},
        ),
    ]
