# Generated by Django 4.0.1 on 2022-09-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_courseinformation_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseinformation',
            constraint=models.UniqueConstraint(fields=('subject_code',), name='unique_classified'),
        ),
    ]
