# Generated by Django 4.0.1 on 2022-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_courseinformation_unique_classified'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseinformation',
            name='unique_classified',
        ),
        migrations.AddConstraint(
            model_name='courseinformation',
            constraint=models.UniqueConstraint(fields=('subject_code', 'course_group', 'campus_name', 'subject_name', 'qualification_name', 'faculty_school_name', 'semester', 'lecturer_code', 'level', 'academic_year', 'department_name'), name='unique_classified_course'),
        ),
    ]
