# Generated by Django 4.0.1 on 2022-09-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_courseinformation_unique_classified_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseinformation',
            name='unique_classified_course',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='course_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.courseinformation'),
        ),
        migrations.AddConstraint(
            model_name='courseinformation',
            constraint=models.UniqueConstraint(fields=('academic_year', 'subject_code', 'course_group', 'campus_name', 'subject_name', 'qualification_name', 'faculty_school_name', 'semester', 'lecturer_code', 'level', 'academic_year', 'department_name'), name='unique_classified_course'),
        ),
    ]
