# Generated by Django 4.0.1 on 2022-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_evaluation_course_information'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseinformation',
            name='unique_classified_course',
        ),
        migrations.AddConstraint(
            model_name='courseinformation',
            constraint=models.UniqueConstraint(fields=('subject_code', 'course_group', 'campus_name', 'subject_name', 'qualification_name', 'faculty_school_name', 'semester', 'lecturer_code', 'level', 'department_name'), name='unique_classified_course'),
        ),
    ]
