# Generated by Django 4.0.1 on 2022-09-03 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturer_code', models.IntegerField(blank=True, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.SmallIntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('000', 'Diploma'), ('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('600', 'Level 600-PGD'), ('700', 'Level 700'), ('800', 'Level 800')], max_length=30, null=True)),
                ('course_group', models.CharField(blank=True, choices=[('day', 'Day'), ('evening', 'Evening'), ('weekend', 'Weekend')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Course Data',
                'verbose_name_plural': 'Course Data',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('course_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluation', to='core.courseinformation')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Reports',
            },
        ),
        migrations.CreateModel(
            name='ProgramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_feedback_beginning_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_course_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_lecture_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_outcomes_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_procedures_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_books_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_schedule', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_punctuality', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_presence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_enthusiasm', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_sequence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_organization', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_clarity', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_contents', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_responsiveness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_achievements', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_innovation', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_theory_practices', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_relevance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_promptitude', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_feedback', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_guidance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_availability', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_help', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_fairness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_classroom_size', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_seats', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_audio_visual_equip', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_public_address', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_books', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_computers', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_internet', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_air_conditioning', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_secretariat', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('evaluationInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_form', to='core.evaluation')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseinformation',
            constraint=models.UniqueConstraint(fields=('academic_year', 'subject_code', 'course_group', 'campus_name', 'subject_name', 'qualification_name', 'faculty_school_name', 'semester', 'lecturer_code', 'level', 'department_name'), name='unique_classified_course'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationsubmission',
            unique_together={('evaluationInfo',)},
        ),
    ]
